server:
  port: 8080
spring:
  application:
    name: joseonpaldo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true    
    show-sql: true
    database: mysql 
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_PASSWORD}
            scope: profile, email
            redirect-uri: "http://localhost:8080/api/auth/signin/callback/google"
            authorization-grant-type: authorization_code
            client-name: google
          kakao:
            client-id: ${KAKAO_RESTAPI_KEY}
            scope: profile, email
            redirect-uri: "http://localhost:8080/api/auth/signin/callback/kakao"
            authorization-grant-type: authorization_code
            client-name: kakao
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/api/auth/signin/callback/naver"
            authorization-grant-type: authorization_code
            client-name: naver
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
jwt:
  rsa:
    secret_key: ${JWT_SECRET_KEY}
    public_key: ${JWT_PUBLIC_KEY}





